name: crowdin

on:
  push:
    branches: [ main ]
    paths: 
      - 'webui/public/locales/strings/*.xml'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Crowdin Action
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
        download_translations: true
        skip_untranslated_files: false
        skip_untranslated_strings: true

        create_pull_request: true
        localization_branch_name: crowdin_branch
        pull_request_labels: 'enhancement, translation'
        pull_request_title: 'opt: sync translation from Crowdin'

        config: 'crowdin.yml'
        crowdin_branch_name: main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}

  upload-translations:
    runs-on: ubuntu-latest
    needs: synchronize-with-crowdin
    steps:
    - name: Checkout translation branch
      uses: actions/checkout@v5
      with:
        ref: 'crowdin_branch'

    - name: Create timestamp
      run: date +%Y%m%d > webui/public/locales/version

    - name: Upload locales folder
      uses: actions/upload-artifact@v5
      with:
        name: locales
        path: webui/public/locales
        
    - name: Checkout bot
      uses: actions/checkout@v5
      with:
        ref: 'bot'

    - name: Download translation
      uses: actions/download-artifact@v5
      with:
        name: locales
        path: locales

    - name: Push to bot branch
      run: |
        rm -f locales_version locales.zip
        cd locales
        cp version ../locales_version
        zip -r ../locales.zip .
        cd ..

        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add locales.zip locales_version
        git commit -m "update locales"
        git push
